// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD95SXyoDkvauq8p_y1gjbWPt800c-9CrI',
    appId: '1:432421295894:android:fffbfc2cd2608489eee237',
    messagingSenderId: '432421295894',
    projectId: 'fashion-shopping-366319',
    storageBucket: 'fashion-shopping-366319.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXJAUT4nF-Bo-7SKfg1H5_xUy0YVnJBZc',
    appId: '1:432421295894:ios:6c2054844695c433eee237',
    messagingSenderId: '432421295894',
    projectId: 'fashion-shopping-366319',
    storageBucket: 'fashion-shopping-366319.appspot.com',
    androidClientId: '432421295894-52alke6fmn0km309949ahl8p7nnef738.apps.googleusercontent.com',
    iosClientId: '432421295894-5crh8hmt49769f253dfsaauq7b08n3qo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fashionShoppingApp',
  );
}
